services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - 3001:3000

  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - 3002:3000

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - 3003:3000 

  nginx:
    image: nginx
    ports: 
      - 8080:80 
    volumes:
      - ./app.js:/usr/share/nginx/html/index.html
      - ./nginx_confg/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_confg/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3     
